name: drag_and_drop_lists
description: A flutter package to allow drag-and-drop reordering of two-level lists.
version: 0.4.2
homepage: https://github.com/philip-brink/DragAndDropLists

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: "^3.27.2"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

